/** Kenya's 47 counties, used for listing locations and the browse filter. */
export const COUNTIES = [
  "Nairobi",
  "Mombasa",
  "Kisumu",
  "Nakuru",
  "Kiambu",
  "Machakos",
  "Kajiado",
  "Uasin Gishu",
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kakamega",
  "Kericho",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Murang'a",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;

export type County = (typeof COUNTIES)[number];

export function isCounty(value: string): value is County {
  return (COUNTIES as readonly string[]).includes(value);
}
